WITH CTE1 AS (
    SELECT
        DISTINCT C.CAR_ID
        , C.CAR_TYPE
        , C.DAILY_FEE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE
        C.CAR_TYPE IN ("세단", "SUV")
        AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE 
                START_DATE <= "2022-11-30"
                AND END_DATE >= "2022-11-01"
        )
), CTE2 AS (
    SELECT
        CAR_TYPE
        , DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE
        CAR_TYPE IN ("세단", "SUV")
        AND DURATION_TYPE = "30일 이상"
)

SELECT
    CTE1.CAR_ID
    , CTE1.CAR_TYPE
    , ROUND((CTE1.DAILY_FEE * (1-(CTE2.DISCOUNT_RATE)/100)) * 30, 0) AS FEE
FROM 
    CTE1
INNER JOIN CTE2
    ON CTE1.CAR_TYPE = CTE2.CAR_TYPE
WHERE
    ROUND((CTE1.DAILY_FEE * (1-(CTE2.DISCOUNT_RATE)/100)) * 30, 0) BETWEEN 500000 AND 1999999
ORDER BY
    3 DESC, 2, 1 DESC