WITH CTE1 AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
), CTE2 AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
)

SELECT
    CTE1.CART_ID
FROM
    CTE1
INNER JOIN CTE2
    ON CTE1.CART_ID = CTE2.CART_ID
ORDER BY
    1