-- 코드를 작성해주세요
WITH CTE AS (
    SELECT
        CASE
            WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('01', '02', '03') THEN '1Q'
            WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('04', '05', '06') THEN '2Q'
            WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('07', '08', '09') THEN '3Q'
            WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('10', '11', '12') THEN '4Q'
        END AS QUARTER
    FROM
        ECOLI_DATA
)
SELECT
    QUARTER,
    COUNT(QUARTER) AS ECOLI_COUNT
FROM
    CTE
GROUP BY
    QUARTER
ORDER BY
    1
