SELECT 
    BOOK.AUTHOR_ID
    , AUTHOR.AUTHOR_NAME
    , BOOK.CATEGORY
    , SUM(BOOK_SALES.SALES * BOOK.PRICE) AS TOTAL_SALES
FROM BOOK
    LEFT JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    LEFT JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE 
    BOOK_SALES.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY
    BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY
    BOOK.AUTHOR_ID ASC
    , BOOK.CATEGORY DESC