SELECT 
    P.PRODUCT_ID
    , P.PRODUCT_NAME
    , SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM
    FOOD_ORDER O
INNER JOIN FOOD_PRODUCT P
    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE
    P.PRODUCT_ID IN (
        SELECT 
            PRODUCT_ID  
        FROM
            FOOD_ORDER
        GROUP BY 
            PRODUCT_ID
        HAVING
            PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
    )
GROUP BY
    P.PRODUCT_ID
ORDER BY
    3 DESC, 1 ASC