-- 코드를 작성해주세요


SELECT
    IT.ITEM_ID,
    II2.ITEM_NAME,
    II2.RARITY
FROM
    ITEM_TREE IT
LEFT JOIN
    ITEM_INFO II
    ON II.ITEM_ID = IT.PARENT_ITEM_ID
LEFT JOIN
    ITEM_INFO II2
    ON IT.ITEM_ID = II2.ITEM_ID
WHERE
    II.RARITY = "RARE"
ORDER BY
    1 DESC;