-- 코드를 작성해주세요

SELECT
    DEV.ID,
    DEV.EMAIL,
    DEV.FIRST_NAME,
    DEV.LAST_NAME
FROM
    DEVELOPERS DEV
WHERE
    SKILL_CODE & (SELECT SC.CODE FROM SKILLCODES SC WHERE NAME = 'C#')
    OR SKILL_CODE & (SELECT SC.CODE FROM SKILLCODES SC WHERE NAME ='Python')
ORDER BY
    ID ASC;