-- 코드를 작성해주세요
WITH A AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    A.MAX_SIZE - ED.SIZE_OF_COLONY AS YEAR_DEV,
    ED.ID AS ID
FROM
    ECOLI_DATA ED
LEFT JOIN A 
    ON A.YEAR = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY
    1, 2
