SELECT
    APNT.APNT_NO
    , PT.PT_NAME
    , PT.PT_NO
    , APNT.MCDP_CD
    , DR.DR_NAME
    , APNT.APNT_YMD
FROM
    APPOINTMENT APNT
LEFT JOIN PATIENT PT ON APNT.PT_NO = PT.PT_NO
LEFT JOIN DOCTOR DR ON APNT.MDDR_ID = DR.DR_ID
WHERE
    DATE_FORMAT(APNT.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND APNT.MCDP_CD = "CS"
    AND APNT.APNT_CNCL_YN = "N"
ORDER BY
    APNT.APNT_YMD ASC